// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkUrPvf-2aT7HwW0rmfviTXR-ZRwuYds',
    appId: '1:704333301875:web:ca87d4516ec7ae25350206',
    messagingSenderId: '704333301875',
    projectId: 'turkcell-project-10f99',
    authDomain: 'turkcell-project-10f99.firebaseapp.com',
    storageBucket: 'turkcell-project-10f99.firebasestorage.app',
    measurementId: 'G-820YZ6JH2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBerlBLDXCsB0nfL-yClODoaDG7QqKis',
    appId: '1:704333301875:android:72d66c22c66b6855350206',
    messagingSenderId: '704333301875',
    projectId: 'turkcell-project-10f99',
    storageBucket: 'turkcell-project-10f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-h27ESRhu4UOvyMvgj_4IvuYpgSQYP8',
    appId: '1:704333301875:ios:e1986a4d58844a48350206',
    messagingSenderId: '704333301875',
    projectId: 'turkcell-project-10f99',
    storageBucket: 'turkcell-project-10f99.firebasestorage.app',
    iosBundleId: 'com.example.turkcellProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-h27ESRhu4UOvyMvgj_4IvuYpgSQYP8',
    appId: '1:704333301875:ios:e1986a4d58844a48350206',
    messagingSenderId: '704333301875',
    projectId: 'turkcell-project-10f99',
    storageBucket: 'turkcell-project-10f99.firebasestorage.app',
    iosBundleId: 'com.example.turkcellProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGkUrPvf-2aT7HwW0rmfviTXR-ZRwuYds',
    appId: '1:704333301875:web:8ed485b3e98ab7ee350206',
    messagingSenderId: '704333301875',
    projectId: 'turkcell-project-10f99',
    authDomain: 'turkcell-project-10f99.firebaseapp.com',
    storageBucket: 'turkcell-project-10f99.firebasestorage.app',
    measurementId: 'G-W3Q0EGTS7F',
  );
}
